### ISSUE TITLE
Possible issue with Pathname vs String incompatibility

### ISSUE THREAD

**Issue by dssjoblom** [capistrano-plugins/capistrano-secrets-yml#6]
When running

`bundle exec cap production secrets_yml:setup
`

I get the following error:
```

NoMethodError: undefined method `start_with?' for #<Pathname:PATH/config/secrets.yml>
/RVM/gems/ruby-2.4.1/gems/sshkit-1.15.0/lib/sshkit/backends/netssh.rb:66:in `upload!'
/RVM/gems/ruby-2.4.1/gems/capistrano-secrets-yml-1.0.0/lib/capistrano/tasks/secrets_yml.rake:42:in `block (3 levels) in <top (required)>'

```

I was able to fix the problem by modifying the rake task, but someone else might run into this.

**Comment by NorseGaud** [comment]
Can you use 1.1.0? See if you can still replicate the problem with the new version and let me know.

**Comment by mark579** [comment]
I am seeing the exact same issue. I couldn't find a 1.1.0 in ruby gems so I pointed my Gemfile at github master branch and the issue is still occurring.

**Comment by NorseGaud** [comment]
@bruno- , could you add my permissions to add new releases to rubygems please? Thanks!
@mark579, the new version doesn't use upload! anymore. Can you provide the full error you're getting?

**Comment by mark579** [comment]
Here is the full error with trace. 

`❯ cap crt secrets_yml:setup --trace
** Invoke crt (first_time)
** Execute crt
** Invoke load:defaults (first_time)
** Execute load:defaults
** Invoke bundler:map_bins (first_time)
** Invoke passenger:bundler:hook (first_time)
** Execute passenger:bundler:hook
** Execute bundler:map_bins
** Invoke deploy:set_rails_env (first_time)
** Execute deploy:set_rails_env
** Invoke deploy:set_linked_dirs (first_time)
** Execute deploy:set_linked_dirs
** Invoke deploy:set_rails_env
** Invoke secrets_yml:setup (first_time)
** Invoke secrets_yml:check (first_time)
** Execute secrets_yml:check
** Invoke secrets_yml:check_secrets_file_exists (first_time)
** Execute secrets_yml:check_secrets_file_exists
** Invoke secrets_yml:check_git_tracking (first_time)
** Execute secrets_yml:check_git_tracking
** Invoke secrets_yml:check_config_present (first_time)
** Execute secrets_yml:check_config_present
** Execute secrets_yml:setup
00:00 secrets_yml:setup
      01 mkdir -pv /srv/workflowdb/shared/config
    ✔ 01 deploy@corpmexcrt00.cerner.com 0.212s
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as deploy@corpmexcrt00.cerner.com: undefined method `start_with?' for #<Pathname:/srv/workflowdb/shared/config/secrets.yml>
/Users/md0190/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sshkit-1.15.0/lib/sshkit/runners/parallel.rb:15:in `rescue in block (2 levels) in execute'
/Users/md0190/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sshkit-1.15.0/lib/sshkit/runners/parallel.rb:11:in `block (2 levels) in execute'

Caused by:
NoMethodError: undefined method `start_with?' for #<Pathname:/srv/workflowdb/shared/config/secrets.yml>
/Users/md0190/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sshkit-1.15.0/lib/sshkit/backends/netssh.rb:66:in `upload!'
/Users/md0190/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/capistrano-secrets-yml-1.0.0/lib/capistrano/tasks/secrets_yml.rake:42:in `block (3 levels) in <top (required)>'
/Users/md0190/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sshkit-1.15.0/lib/sshkit/backends/abstract.rb:29:in `instance_exec'
/Users/md0190/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sshkit-1.15.0/lib/sshkit/backends/abstract.rb:29:in `run'
/Users/md0190/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sshkit-1.15.0/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
Tasks: TOP => secrets_yml:setup`

**Comment by NorseGaud** [comment]
> capistrano-secrets-yml-1.0.0
Make sure to uninstall the old gem, then download https://github.com/capistrano-plugins/capistrano-secrets-yml/releases/tag/1.1.0 and rake install or gem build *.gemspec && gem install *.gem from your CLI. I'm still waiting on access to deploy the new version to rubygems. 

Let me know if the error persists. Also, I've never had luck specifying the github source directly for bundler. It always still installs the wrong version. I'd avoid that too.

Thanks for the quick reply!

**Comment by NorseGaud** [comment]
@mark579, new version 1.1.0 is now in Rubygems.org. Let me know if that solves your issue.
